//! Who owns a generated path, decided before anyone writes it.
//!
//! Generated files are where ownership goes wrong quietly. Two cards run the
//! same generator, both commit the output, and the conflict surfaces at merge
//! as a diff nobody wrote by hand — or worse, one silently wins. The fix is not
//! better merging; it is deciding *in advance* which of four things a path is,
//! because each one implies a different owner:
//!
//! - **transient** belongs to nobody and is never committed;
//! - **per-card** belongs to one card and is generated from sources it owns;
//! - **shared** belongs to integration, so no card may commit it;
//! - **serialized** belongs to whoever was allocated the identifier first.
//!
//! A path with no class is the failure this module exists to prevent, so the
//! class is required rather than defaulted.

use serde::{Deserialize, Serialize};

use crate::error::{ErrorCode, HarnessError};

/// What kind of generated path this is, and therefore who owns it.
#[derive(Clone, Copy, Debug, Deserialize, Serialize, Eq, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactClass {
    /// Build output. Never committed by anyone.
    Transient,
    /// Generated by one card from sources inside its own write scope.
    PerCard,
    /// Generated once during integration; no card may commit it.
    Shared,
    /// Carries an identifier allocated before work, so two cards cannot race
    /// for the same one. Migration numbers are the usual case.
    Serialized,
}

impl ArtifactClass {
    /// Its stable serialized name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Transient => "transient",
            Self::PerCard => "per_card",
            Self::Shared => "shared",
            Self::Serialized => "serialized",
        }
    }

    /// True when a card is permitted to commit a path of this class.
    #[must_use]
    pub const fn card_may_commit(self) -> bool {
        matches!(self, Self::PerCard | Self::Serialized)
    }
}

/// One declared generated path.
#[derive(Clone, Debug, Deserialize, Serialize, Eq, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct GeneratedArtifact {
    /// The path, relative to the repository root.
    pub path: String,
    /// Which of the four kinds it is.
    pub class: ArtifactClass,
    /// The registered gate that regenerates it.
    ///
    /// Required for every class except transient: if nobody can say how a
    /// committed file is produced, nobody can check that it still matches its
    /// sources, and it is an ordinary file wearing a generated label.
    #[serde(default)]
    pub generator: Option<String>,
    /// For a per-card artifact, the sources it is generated from.
    #[serde(default)]
    pub sources: Vec<String>,
    /// For a serialized artifact, the identifier allocated before work.
    #[serde(default)]
    pub identifier: Option<String>,
}

impl GeneratedArtifact {
    /// Checks one declaration against what its class requires.
    ///
    /// # Errors
    ///
    /// Returns a policy error naming the path and what it is missing.
    pub fn validate(&self) -> Result<(), HarnessError> {
        if self.path.trim().is_empty() {
            return Err(invalid("a generated artifact must name a path"));
        }

        match self.class {
            ArtifactClass::Transient => {
                if self.generator.is_some() {
                    return Err(invalid(format!(
                        "transient artifact `{}` names a generator; nothing regenerates a file that is never committed",
                        self.path
                    )));
                }
            }
            ArtifactClass::PerCard => {
                if self.generator.is_none() {
                    return Err(invalid(format!(
                        "per-card artifact `{}` must name the gate that regenerates it",
                        self.path
                    )));
                }
                if self.sources.is_empty() {
                    return Err(invalid(format!(
                        "per-card artifact `{}` must name the sources it is generated from, or nothing can tell whether it is stale",
                        self.path
                    )));
                }
            }
            ArtifactClass::Shared => {
                if self.generator.is_none() {
                    return Err(invalid(format!(
                        "shared artifact `{}` must name the gate integration runs to produce it",
                        self.path
                    )));
                }
            }
            ArtifactClass::Serialized => {
                if self
                    .identifier
                    .as_ref()
                    .is_none_or(|id| id.trim().is_empty())
                {
                    return Err(invalid(format!(
                        "serialized artifact `{}` must carry the identifier allocated before work; allocating it later is the race this class exists to prevent",
                        self.path
                    )));
                }
            }
        }
        Ok(())
    }
}

/// Builds a policy error for an invalid declaration.
fn invalid(reason: impl Into<String>) -> HarnessError {
    HarnessError::Control {
        reason: reason.into(),
        code: ErrorCode::PolicyInvalidArtifact,
    }
}

/// Refuses a set of declarations that assigns a path more than one class.
///
/// # Errors
///
/// Returns a policy error naming the path and the classes claimed for it.
pub fn require_one_class_each(artifacts: &[GeneratedArtifact]) -> Result<(), HarnessError> {
    for (index, artifact) in artifacts.iter().enumerate() {
        artifact.validate()?;
        if let Some(other) = artifacts[..index]
            .iter()
            .find(|earlier| earlier.path == artifact.path)
        {
            return Err(invalid(format!(
                "generated path `{}` is declared as both `{}` and `{}`; each path has exactly one owner",
                artifact.path,
                other.class.name(),
                artifact.class.name()
            )));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn artifact(path: &str, class: ArtifactClass) -> GeneratedArtifact {
        GeneratedArtifact {
            path: path.to_owned(),
            class,
            generator: matches!(class, ArtifactClass::PerCard | ArtifactClass::Shared)
                .then(|| "gate.generate".to_owned()),
            sources: if class == ArtifactClass::PerCard {
                vec!["src/schema.toml".to_owned()]
            } else {
                Vec::new()
            },
            identifier: (class == ArtifactClass::Serialized).then(|| "0007".to_owned()),
        }
    }

    #[test]
    fn each_class_accepts_a_well_formed_declaration() {
        for class in [
            ArtifactClass::Transient,
            ArtifactClass::PerCard,
            ArtifactClass::Shared,
            ArtifactClass::Serialized,
        ] {
            artifact("build/out.js", class)
                .validate()
                .unwrap_or_else(|error| panic!("{} should be valid: {error}", class.name()));
        }
    }

    #[test]
    fn a_per_card_artifact_without_sources_is_refused() {
        let mut declared = artifact("src/generated.rs", ArtifactClass::PerCard);
        declared.sources.clear();
        let error = declared.validate().expect_err("sources are required");
        assert!(error.to_string().contains("sources"), "{error}");
    }

    #[test]
    fn a_committed_class_must_name_its_generator() {
        for class in [ArtifactClass::PerCard, ArtifactClass::Shared] {
            let mut declared = artifact("src/generated.rs", class);
            declared.generator = None;
            declared
                .validate()
                .expect_err("a committed generated file needs a generator");
        }
    }

    #[test]
    fn a_serialized_artifact_must_carry_its_allocated_identifier() {
        let mut declared = artifact("migrations/0007.sql", ArtifactClass::Serialized);
        declared.identifier = None;
        let error = declared.validate().expect_err("an identifier is required");
        assert!(
            error.to_string().contains("allocated before work"),
            "{error}"
        );

        // Whitespace is not an allocation either.
        declared.identifier = Some("   ".to_owned());
        declared.validate().expect_err("blank is not an identifier");
    }

    #[test]
    fn a_transient_artifact_naming_a_generator_is_refused() {
        // Not pedantry: a generator on a transient path means someone believes
        // it is regenerated and checked, and nothing checks a file that is
        // never committed.
        let mut declared = artifact("target/debug/app", ArtifactClass::Transient);
        declared.generator = Some("gate.build".to_owned());
        declared
            .validate()
            .expect_err("transient takes no generator");
    }

    #[test]
    fn one_path_cannot_hold_two_classes() {
        let error = require_one_class_each(&[
            artifact("src/generated.rs", ArtifactClass::PerCard),
            artifact("src/generated.rs", ArtifactClass::Shared),
        ])
        .expect_err("a path has exactly one owner");
        assert!(error.to_string().contains("per_card"), "{error}");
        assert!(error.to_string().contains("shared"), "{error}");
    }

    #[test]
    fn only_per_card_and_serialized_paths_may_be_committed_by_a_card() {
        assert!(ArtifactClass::PerCard.card_may_commit());
        assert!(ArtifactClass::Serialized.card_may_commit());
        assert!(!ArtifactClass::Shared.card_may_commit());
        assert!(!ArtifactClass::Transient.card_may_commit());
    }
}
